const express  = require('express')
const router = express.Router()
const add_data = require('../controllers/add_data')
const isAuth = require('../middleware/proetection')


router.get('/' ,isAuth,add_data.get_home)
router.get('/add-class' ,isAuth,add_data.get_add_class)
router.post('/add-class',isAuth,add_data.post_add_class)
router.get('/add-section' ,isAuth,add_data.get_add_section)
router.post('/add-section' ,isAuth,add_data.post_add_section)
router.get('/add-student',isAuth,add_data.get_add_student_data)
router.get('/student-list',isAuth,add_data.get_student_list)
router.post('/ajax_post_student',add_data.ajax_post_student)
router.post('/ajax_find_section',isAuth,add_data.ajax_find_section)
router.post('/ajax_find_students',isAuth,add_data.get_student_list_by_section)
router.get('/edit-student/:id',isAuth,add_data.get_edit_student)
router.post('/edit-student',isAuth,add_data.post_edit_student)
router.post('/ajax-delete-student',isAuth,add_data.delete_student)
router.get('/add-teacher',isAuth,add_data.add_teacher)
router.post('/add-teacher',isAuth,add_data.post_add_teacher)
router.post('/change-teacher-pass',isAuth,add_data.post_teacher_change_pass)
router.get('/edit-teacher/:id',isAuth,add_data.get_edit_teacher)
router.post('/edit-teacher',isAuth,add_data.post_edit_teacher)
router.post('/ajax-delete-teacher',isAuth,add_data.delete_teacher)
router.get('/add-subject',isAuth,add_data.get_add_subject)
router.get('/add-notice-to-students',isAuth,add_data.add_notice_to_students)
router.post('/add-notice-to-students',isAuth,add_data.post_add_notice_to_students)
router.get('/add-driver',isAuth,add_data.get_add_driver)
router.post('/add-driver',isAuth,add_data.post_add_driver)
router.post('/ajax_post_subject',isAuth,add_data.ajax_post_subject)
router.get('/add-bus',isAuth,add_data.get_add_bus)
router.post('/add-bus',isAuth,add_data.post_add_bus)
router.get('/login',add_data.login)

router.post('/login',add_data.post_login)

router.post('/logout',isAuth,add_data.post_logout)

module.exports =  router
